name: 'Issue Marker'
description: 'Mark an issue which has been merged into a stage'
author: 'Rojan Gh.'
inputs:
    token:
      required: true
      description: Token
    reference:
      required: true
      description: Git Reference
    version:
      required: true
      description: Release Version
    previous-version:
      required: false
      description: Previous Release Version
      default: ''
    close-issues:
      required: false
      default: 'true'
      description: Close Issues on Merge to Production
    zenhub-key:
      default: ''
      required: false
      description: ZenHub's API Key
    zenhub-workspace:
      default: ''
      required: false
      description: ZenHub's Workspace Id
runs:
  using: 'node16'
  main: 'dist/index.js'
